### PR TITLE
Create KeepAliveInterval and KeepAliveStartFrom to control keep-alive packet

### PR DESCRIPTION
**Pull request by andysim3d**
I add 2 configuration attributes to control keep alive option, so users could use them to control time interval of sending keep alive packet, and avoid idle connection.

### CODE REVIEW

**Comment by enyim** [comment]
Looks useful, thanks. However, before merging, can you please make sure that your code follows the style of the rest of the code base?

- tabs, instead of spaces
- private fields should not have underscore as prefixes
- primitive types are lowercase (byte vs Byte)
- private fields are grouped together
- etc

Also, why do we have two different keepalive settngs? Why is it useful to start sending the packets later/earlier than the interval is?

**Comment by enyim** [comment]
+1

Can you please squash the two commits into one?

**Comment by andysim3d** [comment]
updated.
The Keep alive interval is to decide the time interval of sending every 2 keep alive packets.
The Keep alive starts from is to decide when to start send the keep alive packets.
It's like most time, we do not need the tcp connection send keep alive packet in the first 30 mins( suppose most short time connections will be closed within 30 mins). If the connection is still working after 30 mins, to keep it reliable and not closed by some OS/ FW rules, we decide to send keep alive packets as heartbeat for every 5 mins.

**Comment by enyim** [comment]
Merged (had to do some minor editing)

**Pull request closed without merging**
